Models/ContactUs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MultipageApp.Models {
    public class ContactUs {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string  Email { get; set; }
        public string  Phone { get; set; }
        public string Message { get; set; }
    }
}

Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

namespace MultipageApp.Controllers {
    public class AboutController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MultipageApp.Controllers {
	public class AppController : Controller {
		public IActionResult Index() {
			return View();
		}
	}
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

namespace MultipageApp.Controllers {
    public class ContactController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MultipageApp.Controllers {
    public class HomeController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

namespace MultipageApp.Controllers {
    public class PrivacyController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

namespace MultipageApp.Controllers {
    public class ServicesController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Views/About/Index.cshtml
@{
    ViewData["Title"] = "About";
}
<div>
	<app-welcome></app-welcome>
</div>
<h1>About Us </h1>

Views/App/Index.cshtml
@{
	ViewData["Title"] = "Angular App";
}

<iframe src="/angularapps/childapp/@Model" class="app-container" frameborder="0" scrolling="no" width="100%" height="600px"></iframe>

Views/Contact/Index.cshtml
@model MultipageApp.Models.ContactUs

@{
    ViewData["Title"] = "Contact Us";
}
<div>
	<app-welcome></app-welcome>
</div>
<h4>Contact us</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fullname" class="control-label"></label>
                <input asp-for="Fullname" class="form-control" />
                <span asp-validation-for="Fullname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div>
	<app-welcome></app-welcome>
</div>
<h1>Home View </h1>

Views/Privacy/Index.cshtml
@{
    ViewData["Title"] = "Privacy";
}
<div>
	<app-welcome></app-welcome>
</div>
<h1>Privacy Statement</h1>

Views/Services/Index.cshtml
@{
    ViewData["Title"] = "Services";
}
<div>
	<app-welcome></app-welcome>
</div>
<h1>Services Section</h1>

Views/Shared/_AppLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
APP LAyout
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_MasterLayout.cshtml
<!DOCTYPE html>

<html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	<link rel="stylesheet" href="~/wwwroot/css/Styles.css" />
	<title>@ViewBag.Title</title>
</head>

<body>
	<header class="mb-1">
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" asp-controller="Home" asp-action="Index">Bit of Ai</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<li class="nav-item">
							<a class="nav-link" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-controller="Services" asp-action="Index">Services</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-controller="About" asp-action="Index">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-controller="Contact" asp-action="Index">Contact</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-controller="App" asp-action="Index" >App</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

	</header>
	<div class="px-1">
		
		<div>
			@RenderBody()
		</div>
	</div>
	<footer class="border-top footer text-muted">
		<div class="px-1">
			&copy; 2021 Bit of Ai <a asp-controller="Privacy" asp-action="Index">Privacy </a>
		</div>
	</footer>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script asp-src-include="~/parentapp/runtime.*.js" type="module"></script>
	<script asp-src-include="~/parentapp/polyfills.*.js" type="module"></script>
	<script asp-src-include="~/parentapp/main.*.js" type="module"></script>
	<script asp-src-include="~/parentapp/styles.*.css" ></script>
	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>